name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          make install_dependencies

      - name: Build shell
        run: make shell

      - name: Rename binary and make executable
        run: |
          mv build/shell BCRZ-x86_64-linux

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./BCRZ-x86_64-linux
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
