name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          make install_dependencies

      - name: Build shell (statically linked)
        run: |
          make shell

      - name: Rename binary
        run: |
          VERSION=${GITHUB_REF_NAME##*/}
          mv build/shell shell-${VERSION}-x86_64-linux
          chmod +x shell-${VERSION}-x86_64-linux

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./shell-*-x86_64-linux
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
