name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build with make
        run: make install_dependencies shell

      - name: Rename binary
        run: |
          VERSION=${GITHUB_REF_NAME}
          mv ./build/shell ./shell-${VERSION}-x86_64-linux

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: shell
          path: ./shell-*-x86_64-linux

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: shell

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./shell-*-x86_64-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
